### ISSUE TITLE
add a slider component

### ISSUE THREAD

**Issue by meelijane** [thedavidmeister/estimate-work#149]

**Comment by thedavidmeister** [comment]
http://hoplon.discoursehosting.net/t/defelem-is-it-used-internally-by-hoplon/106/2

**Comment by thedavidmeister** [comment]
<img width="1424" alt="screen shot 2016-03-14 at 3 29 53 pm" src="https://cloud.githubusercontent.com/assets/629710/13735105/a4612096-e9f9-11e5-9014-21eaa8da8fb2.png">
